name: E2E

on:
  push:
    branches:
      - master

jobs:
  e2e_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
          run: npm install
      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:open
          start: npm run start-prod
          wait-on: http://localhost:5000
